Sprint 09
GolovkinEgor/ImageFeed pull request #3
Opened 2024-12-15 22:46 UTC by GolovkinEgor

2024-12-16 08:26 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. Не все изображения выровнены по центру экрана, [см. видео](https://disk.yandex.ru/i/SCNp_sgur2RZLQ). Необходимо поправить в соответствии с пунктом задания 4.
2. Не все элементы экрана профиля были настроены правильно, необходимо поправить в соответствии с пунктом задания 3: 
    1. шрифт необходимо выгрузить и использовать из макетов,
    2. отступ слева у картинки профиля должен быть равен 16, как в макетах
    3. отступ сверху у картинки должен быть равен 32, как в макетах
    4. констрейнты на ширину и высоту у UILabel ставить не нужно, иначе разные имена могут отображаться неккоректно
    5. отступ у иконки выхода справа должен быть равен -16
3. В `SingleImageViewController` у `ScrollView` не были выставлены констрейнты, равные нулю со всех сторон, [см. скриншот](https://ibb.co/mJQnfch). Необходимо поправить в соответствии с пунктом задания 4.

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-12-16 08:26 UTC, Kirchberg commented on ImageFeed/Profile/ProfileViewController.swift
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-12-16 08:26 UTC, Kirchberg commented on ImageFeed/Profile/ProfileViewController.swift
> +        private var  label3:UILabel!
Было бы хорошо вместо label, labelTag и label3 дать осмысленные названия переменных, показать то, что они отражают в макетах

2024-12-16 08:26 UTC, Kirchberg commented on ImageFeed/Profile/ProfileViewController.swift
> +            labelTag.heightAnchor.constraint(equalToConstant: 18).isActive = true
Констрейнты на ширину и высоту у UILabel ставить не нужно, иначе разные имена могут отображаться неккоректно

2024-12-17 08:25 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. Не все изображения выровнены по центру экрана, [см. скриншот](https://ibb.co/3yW0Z0B). Необходимо поправить в соответствии с пунктом задания 4.
2. Не все элементы экрана профиля были настроены правильно, необходимо поправить в соответствии с пунктом задания 3: 
    1. шрифт необходимо выгрузить и использовать из макетов. Сейчас у тебя используются системные шрифты, необходимо взять из макетов шрифты как это было сделано для прошлого проекта.
3. В `SingleImageViewController` у `ScrollView` не были выставлены констрейнты, равные нулю со всех сторон, [см. скриншот](https://ibb.co/mJQnfch). Необходимо поправить в соответствии с пунктом задания 4.

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-12-17 08:25 UTC, Kirchberg commented on ImageFeed/Base.lproj/Main.storyboard
> +                            <constraint firstItem="1qE-B7-E1B" firstAttribute="leading" secondItem="XFn-xa-2Yg" secondAttribute="leading" constant="-20" id="Tf1-qe-GtR"/>
⚠️ Отступы у ScrollView по условиям задания должны быть равны 0

2024-12-17 11:08 UTC, GolovkinEgor commented
Добрый день,а что не так со шрифтами, просто везде сказано что используется SF pro , а это встроенный шрифт ?

2024-12-17 17:39 UTC, Kirchberg commented
> Добрый день,а что не так со шрифтами, просто везде сказано что используется SF pro , а это встроенный шрифт ?

Привет! Извини за недоразумение. Со шрифтами всё в порядке, прошу прощения за беспокойство. Нужно поправить только пункты 1 и 3.

2024-12-19 08:18 UTC, Kirchberg approved these changes
Не забудь вмерджить пул-реквест в основную ветку.
Успехов в следующем задании!

2024-12-21 15:06 UTC, merged